### ISSUE TITLE
Can't open demo example on 4.14.3 (Mac Version)

### ISSUE THREAD

**Issue by gamugamu** [SiggiG/ProceduralMeshDemos#2]
Your demo seems very interesting and promising. I have imported your project and tried to open it with UE 4.14.3 on mac, but UE seems complaining about a compilation problem (the following modules are missing or built with a different engine version: UE4Editor-ProceduralMeshDemos.dylib). 

I've got a log from UE (which say it can't find module rules files for module 'Procedural Meshes'), and all I get is the 'ProceduralMeshDemos could not be compiled; Try rebuilding from source manually' error popup.
Sorry if the problem is not related on your code, but more on UE (I don't understand why it can't first open the project and then make the dependance and compilation). Since I saw you made some commit with UE new version, I think maybe you could help me. I have just started UE today and I'm not totally sure if projects are totally platform independant or support automatic migration. Thanks in advance

**Comment by SiggiG** [comment]
I'm not providing binaries, did you try compiling the source yourself? I guess on the Mac you would use XCode?

**Comment by gamugamu** [comment]
Yes, I need to compile the binaries. But I can't open the project from Unreal, and there is no Xcode project generated. Each time I launch UG with this one, it ends up closing the project because it can't find rules to generate the module.

**Comment by SiggiG** [comment]
Are you trying to compile the demo project directly or just adding the plugin to your project?

If you are just trying to compile the demo project, did you correctly initialize and get the Git submodules?  If you are unsure about submodules, see my UpdateSubmodules.bat as an example.

If you are trying to add the plugin (ProceduralMeshes not ProceduralMeshDemos) to your own project, then you need to add it under Plugins/ and then generate your project files.
