### ISSUE TITLE
UE-Editor crashes when I try to use "SimpleCube_BP"

### ISSUE THREAD

**Issue by luofxgucas** [SiggiG/ProceduralMeshDemos#3]
（1）In the UE-Editor, I drag a "SimpleCube_BP" to the level.
（2）I click the "Play" button and run the scene
（3）UE-Editor gets a crash and give a error "0xC0000005: 0xFFFFFFFFFFFFFFFF can not be read!"

Test environment:
UE 4.19
Win7/64

**Comment by SiggiG** [comment]
Sorry how long it took me to update the project. Should be all good now!

I tried your steps and it doesnt crash any more.
