### ISSUE TITLE
Will not compile under Unreal 4.20

### ISSUE THREAD

**Issue by Drezil** [SiggiG/ProceduralMeshDemos#4]
The dependencies (RuntimeMeshComponent) changed some functions for 4.20 (fenced with #ifdef's) that need to be brought up 2 date.

I open this issue to let others know, while i try to fix it for me (which may take time depending on how complicated things get..).

Prepare for a PR ;)

**Comment by Drezil** [comment]
After https://github.com/SiggiG/ProceduralMeshes/pull/17 (or similar) is merged the git submodule should be updated to reflect that (lift both plugins onto their respective master-branches).

**Comment by SiggiG** [comment]
Done, thanks!
