### ISSUE TITLE
Update to 4.21 causes hard crash in editor

### ISSUE THREAD

**Issue by chrisgundling** [SiggiG/ProceduralMeshDemos#5]
After upgrading ProceduralMeshDemos and the related plugins to Unreal 4.21, pressing simulate causes hard crash of editor with following error: 
```Assertion failed: Mesh.VertexFactory->IsInitialized()```
Everything has worked great up until 4.21. 

Has anyone been successful in getting this to work with 4.21?

OS - Ubuntu 16.04
UE4 - v4.21

**Comment by SiggiG** [comment]
I have updated the project to UE 4.22 + some updates to RMC, and do not get this crash when pressing simulate.  Let me know if you still have this issue.

**Comment by chrisgundling** [comment]
@SiggiG Thanks for the updates! Everything opens up properly in the editor, but then unfortunately I still get a similar error when either hitting simulate or run. Doing a little debugging I found that if I don't generate the meshes on load, then I can create them on BeginPlay, but if you try to update or re-create them when they already exist you get the crash.

OS - Ubuntu 16.04
UE4 - v4.22

```
Assertion failed: Mesh.VertexFactory->IsInitialized() [File:/home/user/UnrealEngine_4.22/Engine/Source/Runtime/Renderer/Private/PrimitiveSceneInfo.cpp] [Line: 54] 

Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554 
CommonUnixCrashHandler: Signal=11
Malloc Size=65535 LargeMemoryPoolOffset=131119 
Malloc Size=695232 LargeMemoryPoolOffset=826368 
[2019.04.10-22.13.18:868][944]LogCore: Error: appError called: Assertion failed: Mesh.VertexFactory->IsInitialized() [File:/home/user/UnrealEngine_4.22/Engine/Source/Runtime/Renderer/Private/PrimitiveSceneInfo.cpp] [Line: 54] 


[2019.04.10-22.13.18:886][944]LogCore: === Critical error: ===
Unhandled Exception: SIGSEGV: invalid attempt to read memory at address 0x0000000000000545

[2019.04.10-22.13.18:886][944]LogCore: Assertion failed: Mesh.VertexFactory->IsInitialized() [File:/home/user/UnrealEngine_4.22/Engine/Source/Runtime/Renderer/Private/PrimitiveSceneInfo.cpp] [Line: 54] 
```

**Comment by SiggiG** [comment]
Damn, sorry to hear that.  Unfortunately that might be out of my control if its in the RuntimeMeshComponent code, which I believe has been semi-abandoned by the author.
There is still a strong Discord for that going though:
https://discord.gg/XEUH2PY
