### ISSUE TITLE
Error when i try to open Proceduralmeshdemos.uproject

### ISSUE THREAD

**Issue by lolo0162** [SiggiG/ProceduralMeshDemos#6]
in unreal 4.24 
The project could not be compiled. Would you like to open it in Visual Studio?

Running C:/Program Files/Epic Games/UE_4.24/Engine/Binaries/DotNET/UnrealBuildTool.exe Development Win64 -Project="F:/Utilisateurs/Laurent/Documents/Unreal Projects/ProceduralMeshDemos-master 4.24 - 2/ProceduralMeshDemos.uproject" -TargetType=Editor -Progress -NoHotReloadFromIDE
Creating makefile for ProceduralMeshDemosEditor (no existing makefile)
F:\Utilisateurs\Laurent\Documents\Unreal Projects\ProceduralMeshDemos-master 4.24 - 2\Plugins\ProceduralMeshes\Source\ProceduralMeshes\ProceduralMeshes.Build.cs: warning: Modules must specify an explicit precompiled header (eg. PrivatePCHHeaderFile = "Private/ProceduralMeshesPrivatePCH.h") from UE 4.21 onwards.
F:\Utilisateurs\Laurent\Documents\Unreal Projects\ProceduralMeshDemos-master 4.24 - 2\Plugins\ProceduralMeshes\Source\ProceduralMeshes\ProceduralMeshes.Build.cs: warning: Referenced directory 'C:\Program Files\Epic Games\UE_4.24\Engine\Source\ProceduralMeshes\Public' does not exist.
F:\Utilisateurs\Laurent\Documents\Unreal Projects\ProceduralMeshDemos-master 4.24 - 2\Source\ProceduralMeshDemos\ProceduralMeshDemos.Build.cs: warning: Modules must specify an explicit precompiled header (eg. PrivatePCHHeaderFile = "ProceduralMeshDemos.h") from UE 4.21 onwards.
WARNING: Warning: Plugin 'ProceduralMeshes' does not list plugin 'RuntimeMeshComponent' as a dependency, but module 'ProceduralMeshes' depends on 'RuntimeMeshComponent'.
@progress push 5%
Parsing headers for ProceduralMeshDemosEditor
  Running UnrealHeaderTool "F:\Utilisateurs\Laurent\Documents\Unreal Projects\ProceduralMeshDemos-master 4.24 - 2\ProceduralMeshDemos.uproject" "F:\Utilisateurs\Laurent\Documents\Unreal Projects\ProceduralMeshDemos-master 4.24 - 2\Intermediate\Build\Win64\ProceduralMeshDemosEditor\Development\ProceduralMeshDemosEditor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -installed
Reflection code generated for ProceduralMeshDemosEditor in 8,2776503 seconds
@progress pop
Building ProceduralMeshDemosEditor...
Using Visual Studio 2017 14.16.27038 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023) and Windows 10.0.16299.0 SDK (C:\Program Files (x86)\Windows Kits\10).
[Upgrade]
[Upgrade] Using backward-compatible build settings. The latest version of UE4 sets the following values by default, which may require code changes:
[Upgrade]     bLegacyPublicIncludePaths = false                 => Omits subfolders from public include paths to reduce compiler command line length. (Previously: true).
[Upgrade]     ShadowVariableWarningLevel = WarningLevel.Error   => Treats shadowed variable warnings as errors. (Previously: WarningLevel.Warning).
[Upgrade]     PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs   => Set in build.cs files to enables IWYU-style PCH model. See https://docs.unrealengine.com/en-US/Programming/BuildTools/UnrealBuildTool/IWYU/index.html. (Previously: PCHUsageMode.UseSharedPCHs).
[Upgrade] Suppress this message by setting 'DefaultBuildSettings = BuildSettingsVersion.V2;' in ProceduralMeshDemosEditor.Target.cs, and explicitly overriding settings that differ from the new defaults.
[Upgrade]
Building 27 actions with 8 processes...
  @progress 'Compiling C++ source code...' 0%
  @progress 'Compiling C++ source code...' 4%
  [1/27] Default.rc2
  @progress 'Compiling C++ source code...' 7%
  [2/27] Default.rc2
  @progress 'Compiling C++ source code...' 11%
  [3/27] Default.rc2
  @progress 'Compiling C++ source code...' 15%
  [4/27] Default.rc2
  @progress 'Compiling C++ source code...' 19%
  [5/27] SharedPCH.UnrealEd.cpp
  @progress 'Compiling C++ source code...' 22%
  [6/27] SharedPCH.Engine.cpp
  @progress 'Compiling C++ source code...' 26%
  [7/27] PCH.ProceduralMeshDemos.cpp
  @progress 'Compiling C++ source code...' 30%
  [8/27] Module.RuntimeMeshComponent.gen.3_of_3.cpp
  @progress 'Compiling C++ source code...' 33%
  [9/27] ProceduralMeshDemos.init.gen.cpp
  @progress 'Compiling C++ source code...' 37%
  [10/27] ProceduralMeshDemos.cpp
  @progress 'Compiling C++ source code...' 41%
  [11/27] ProceduralMeshDemosGameMode.cpp
  @progress 'Compiling C++ source code...' 44%
  [12/27] ProceduralMeshDemosGameMode.gen.cpp
  @progress 'Compiling C++ source code...' 48%
  [13/27] UE4Editor-ProceduralMeshDemos.lib
     Cr?ation de la biblioth?que F:\Utilisateurs\Laurent\Documents\Unreal Projects\ProceduralMeshDemos-master 4.24 - 2\Intermediate\Build\Win64\UE4Editor\Development\ProceduralMeshDemos\UE4Editor-ProceduralMeshDemos.lib et de l'objet F:\Utilisateurs\Laurent\Documents\Unreal Projects\ProceduralMeshDemos-master 4.24 - 2\Intermediate\Build\Win64\UE4Editor\Development\ProceduralMeshDemos\UE4Editor-ProceduralMeshDemos.exp
  @progress 'Compiling C++ source code...' 52%
  [14/27] Module.RuntimeMeshComponentEditor.cpp
  F:/Utilisateurs/Laurent/Documents/Unreal Projects/ProceduralMeshDemos-master 4.24 - 2/Plugins/RuntimeMeshComponent/Source/RuntimeMeshComponentEditor/Private/RuntimeMeshComponentDetails.cpp(490): warning C4996: 'UStaticMesh::SourceModels': Please do not access this member directly; use UStaticMesh::GetSourceModel(LOD) or UStaticMesh::GetSourceModels(). Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
  C:\Program Files\Epic Games\UE_4.24\Engine\Source\Runtime\Engine\Classes\Engine/StaticMesh.h(516): note: voir la d?claration de 'UStaticMesh::SourceModels'
  F:/Utilisateurs/Laurent/Documents/Unreal Projects/ProceduralMeshDemos-master 4.24 - 2/Plugins/RuntimeMeshComponent/Source/RuntimeMeshComponentEditor/Private/RuntimeMeshComponentDetails.cpp(508): warning C4996: 'UStaticMesh::SectionInfoMap': Please do not access this member directly; use UStaticMesh::GetSectionInfoMap(). Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
  C:\Program Files\Epic Games\UE_4.24\Engine\Source\Runtime\Engine\Classes\Engine/StaticMesh.h(521): note: voir la d?claration de 'UStaticMesh::SectionInfoMap'
  F:/Utilisateurs/Laurent/Documents/Unreal Projects/ProceduralMeshDemos-master 4.24 - 2/Plugins/RuntimeMeshComponent/Source/RuntimeMeshComponentEditor/Private/RuntimeMeshComponentDetails.cpp(511): warning C4996: 'UStaticMesh::SectionInfoMap': Please do not access this member directly; use UStaticMesh::GetSectionInfoMap(). Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
  C:\Program Files\Epic Games\UE_4.24\Engine\Source\Runtime\Engine\Classes\Engine/StaticMesh.h(521): note: voir la d?claration de 'UStaticMesh::SectionInfoMap'
  @progress 'Compiling C++ source code...' 56%
  [15/27] UE4Editor-RuntimeMeshComponentEditor.lib
     Cr?ation de la biblioth?que F:\Utilisateurs\Laurent\Documents\Unreal Projects\ProceduralMeshDemos-master 4.24 - 2\Plugins\RuntimeMeshComponent\Intermediate\Build\Win64\UE4Editor\Development\RuntimeMeshComponentEditor\UE4Editor-RuntimeMeshComponentEditor.lib et de l'objet F:\Utilisateurs\Laurent\Documents\Unreal Projects\ProceduralMeshDemos-master 4.24 - 2\Plugins\RuntimeMeshComponent\Intermediate\Build\Win64\UE4Editor\Development\RuntimeMeshComponentEditor\UE4Editor-RuntimeMeshComponentEditor.exp
  @progress 'Compiling C++ source code...' 59%
  [16/27] Module.RuntimeMeshComponent.cpp
  F:/Utilisateurs/Laurent/Documents/Unreal Projects/ProceduralMeshDemos-master 4.24 - 2/Plugins/RuntimeMeshComponent/Source/RuntimeMeshComponent/Private/RuntimeMesh.cpp(7): fatal error C1083: Impossible d'ouvrir le fichier include?: 'Physics/IPhysXCookingModule.h'?: No such file or directory
  @progress 'Compiling C++ source code...' 63%
  [17/27] Module.ProceduralMeshes.gen.cpp
  @progress 'Compiling C++ source code...' 67%
  [18/27] Module.RuntimeMeshComponent.gen.1_of_3.cpp
  @progress 'Compiling C++ source code...' 70%
  [19/27] Module.ProceduralMeshes.cpp
  @progress 'Compiling C++ source code...' 74%
  [20/27] UE4Editor-ProceduralMeshes.lib
     Cr?ation de la biblioth?que F:\Utilisateurs\Laurent\Documents\Unreal Projects\ProceduralMeshDemos-master 4.24 - 2\Plugins\ProceduralMeshes\Intermediate\Build\Win64\UE4Editor\Development\ProceduralMeshes\UE4Editor-ProceduralMeshes.lib et de l'objet F:\Utilisateurs\Laurent\Documents\Unreal Projects\ProceduralMeshDemos-master 4.24 - 2\Plugins\ProceduralMeshes\Intermediate\Build\Win64\UE4Editor\Development\ProceduralMeshes\UE4Editor-ProceduralMeshes.exp
  @progress 'Compiling C++ source code...' 78%
  [21/27] Module.RuntimeMeshComponent.gen.2_of_3.cpp

in visual studio 2017
Gravité	Code	Description	Projet	Fichier	Ligne	État de la suppression
Erreur	C1083	Impossible d'ouvrir le fichier include : 'Physics/IPhysXCookingModule.h' : No such file or directory	ProceduralMeshDemos	F:\Utilisateurs\Laurent\Documents\Unreal Projects\ProceduralMeshDemos-master 4.24\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponent\Private\RuntimeMesh.cpp	7

**Comment by SiggiG** [comment]
Sorry the current version only supports Unreal 4.22.  I'm working on an update to support Unreal 4.25 and the latest RuntimeMeshComponent plugin.

**Comment by SiggiG** [comment]
Fixed, new 4.25 compatible version release.
