### ISSUE TITLE
Cannot Compile in 4.24 4.25

### ISSUE THREAD

**Issue by fpibbs** [SiggiG/ProceduralMeshDemos#7]
Is there any hope to have it compiled for that versions?

**Comment by dvpavlov-dev** [comment]
> Есть ли надежда, что он будет скомпилирован для этих версий?

Also encountered this problem, does not compile on version 4.25

**Comment by SiggiG** [comment]
I'm working on an update now for UE 4.25 and using the latest RuntimeMeshComponent

**Comment by SiggiG** [comment]
Fixed, new 4.25 compatible version release.
